### PR TITLE
Missing oneways

### PR DESCRIPTION
**Pull request by Rub21**
from https://github.com/osmlab/osmlint/issues/116

@geohacker could you check the code?

### CODE REVIEW

**Comment by Rub21** [comment]
@geohacker ^^

**Comment by Rub21** [comment]
@geohacker  ^^

**Comment by geohacker** [comment]
Hey @Rub21 - could you lint and indent the code? Also put some more inline comments to explain? There are a lot of operations that are hard to understand. 

Apologies for taking too long.

**Comment by Rub21** [comment]
@geohacker , I've added the comment in code and the detection is already in to-fix if you want to check the output. http://osmlab.github.io/to-fix/#/task/missingonewaysmotorwaylink 

cc . @planemad

**Comment by Rub21** [comment]
Done to merge!

**Pull request merged**
