### PR TITLE
faster lookup

### PR DESCRIPTION
**Pull request by arunasank**
Convert the array into an object before the lookup.

Thanks @batpad. I finally understand how to use Array.reduce(). 🙇 

cc/ @geohacker.

### CODE REVIEW

**Comment by batpad** [comment]
@arunasank lgtm 👍

**Comment by geohacker** [comment]
Ah this is awesome. Thank you!
@arunasank the tests will most likely fail because the fixtures are not updated.

**Comment by arunasank** [comment]
@geohacker Haven't rebased against the `update` branch(For fixture/tests updation), so should be 🍏

**Comment by geohacker** [comment]
Oh great.

**Pull request merged**
