### PR TITLE
Overlaphighways

### PR DESCRIPTION
**Pull request by Rub21**
This validator find overlap highways. 

@maning  can you check the output. for USA ?https://gist.github.com/anonymous/8552590e7393dc6575b4

@geohacker @batpad can you check out the code?, if we  can do it much faster would be good.
also the task is in to-fix http://osmlab.github.io/to-fix/#/task/overlaphighwaysus
cc. @planemad

### CODE REVIEW

**Comment by maning** [comment]
@rub21 I've tested the output via to-fix and all errors I saw were valid errors.  This linter is good to go output wise.  Passing on to @geohacker and @batpad for code review.

**Comment by geohacker** [comment]
@Rub21 - I think this looks good, but I think we can potentially cut a few conditions. I'd like to get @batpad's eyes as well. 

@Rub21 meanwhile, can you fix the tests? Thank you!

**Comment by Rub21** [comment]
@geohacker  test was fixed.
Time to merge...

**Comment by geohacker** [comment]
@Rub21 :+1:

**Pull request merged**
