### PR TITLE
Strange layer validator

### PR DESCRIPTION
**Pull request by Rub21**
From : https://github.com/osmlab/osmlint/issues/94
Result : https://gist.github.com/anonymous/960ca1fe4642b539ff3dccd73ff0ec36
Time :2 min for USA, (4xlarge)

@maning could you check the result?
@geohacker could you check the code?

cc. @planemad

### CODE REVIEW

**Comment by Rub21** [comment]
@maning @geohacker  any news here?

**Comment by Rub21** [comment]
@geohacker ^^

**Comment by geohacker** [comment]
Hey @Rub21 - the description of this validator says that it `detects highways with less likely turning angles.` I can't seem to figure out where this is happening in the code though. Can you point out?

Also the flag is set to true in both these if conditions - https://github.com/osmlab/osmlint/pull/101/files#diff-70ec1a2e509f3c7000dd41a1238268b4R43 - regardless `valueHighway.properties.layer) > 0 or < 0`. Can you put some inline comments to explain this? 

@maning - could you take a look as well?

**Comment by Rub21** [comment]
@geohacker I've updated the readme and some fixes in code!

**Pull request merged**
