### PR TITLE
Crossing buildings and self intersecting buildings

### PR DESCRIPTION
**Pull request by Rub21**

### CODE REVIEW

**Comment by Rub21** [comment]
from https://github.com/osmlab/osmlint/issues/24#issuecomment-277497153 

- Output for LA: https://s3.amazonaws.com/tofix/la.geojson

@maning  can you check the output?, 
@geohacker  can you check the code as well?

**Comment by geohacker** [comment]
@Rub21 this flags self intersecting as well as overlapping buildings, correct? Code looks alright to me!

**Comment by maning** [comment]
Detection looks good!  However, I'm concerned over the number of points in the geojson file.
screen shot 2017-02-08 at 19 02 27
screen shot 2017-02-08 at 19 02 00

I'm curious how this will be loaded in to-fix, are we showing the points or the polygon?

**Comment by Rub21** [comment]
> I'm curious how this will be loaded in to-fix, are we showing the points or the polygon?

@maning  we are showing the points, that is much better than polygons.

**Comment by Rub21** [comment]
> @Rub21 this flags self intersecting as well as overlapping buildings, correct? Code looks alright to me!

@geohacker  basically we are doing all common errors in buildings, self-intersecting and crossing buildings, The self-intersecting is detected in the first pass, https://github.com/osmlab/osmlint/blob/45f0dc11ee20e44a5dc83dce7f58296723d43a89/validators/crossingBuildings/map.js#L34-L35

and here is detecting the overlap buildings. https://github.com/osmlab/osmlint/blob/45f0dc11ee20e44a5dc83dce7f58296723d43a89/validators/crossingBuildings/map.js#L39-L70

**Comment by maning** [comment]
> we are showing the points, that is much better than polygons.

@Rub21 Can we use polys? For the above case, there will be a lot errors listed but actually only 2 polygons overlap/cross.

**Comment by Rub21** [comment]
@Rub21 Can we use polys? For the above case, there will be a lot errors listed but actually only 2 polygons overlap/cross.

@maning, that is not points, those are multipoint,  OSMLint is throwing MultiPoints for every case.

**Comment by maning** [comment]
@Rub21 was this merged in master, I can't find the crossingBuildings in the validators dir.

**Comment by Rub21** [comment]
@maning  I don't know why it does not appear,  but I added it again on https://github.com/osmlab/osmlint/pull/219

**Pull request merged**
