### PR TITLE
Impossibleangle

### PR DESCRIPTION
**Pull request by Rub21**
From : https://github.com/osmlab/osmlint/issues/83
Time : 10 seg for Peru on my laptop.

@maning, could check the result? https://gist.github.com/anonymous/5fa5095d11c61bb3f1c2906ef4438d2f

@geohacker @batpad  can you take look on code, to merge in master? 

cc. @aaronlidman @planemad

### CODE REVIEW

**Comment by batpad** [comment]
This looks good to me, @Rub21 ! Will see if @geohacker has any inputs, else I'm :+1: on merging.

**Comment by maning** [comment]
Short description: 
Impossible angle: Roads that bend in a very sharp angle.  The current threshold is <10 deg.

@Rub21, is this a better description.

**Comment by geohacker** [comment]
@Rub21 just updated the readme based on what @maning suggested. This looks good! :tada:

**Comment by Rub21** [comment]
@geohacker @maning , I've just merged.

**Pull request merged**
